services:
  neuralnexus.web:
    image: ${DOCKER_REGISTRY-}neuralnexusweb
    build:
      context: .
      dockerfile: src/NeuralNexus.Web/Dockerfile

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    tty: true
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    runtime: nvidia

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=ABC'    
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

  n8n:
      image: docker.n8n.io/n8nio/n8n
      container_name: n8n
      ports:
        - "5678:5678"
      volumes:
        - n8n_data:/home/node/.n8n

volumes:
  ollama:
  open-webui:
  n8n_data:
